# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sempl_lrt <- function(weights, y, b_r, o_r, innerTol, maxInnerIter, aelWeight) {
    .Call('_empLikSem_sempl_lrt', PACKAGE = 'empLikSem', weights, y, b_r, o_r, innerTol, maxInnerIter, aelWeight)
}

semplC <- function(weights, y, b_r, o_r, innerTol, maxInnerIter, aelWeight) {
    .Call('_empLikSem_semplC', PACKAGE = 'empLikSem', weights, y, b_r, o_r, innerTol, maxInnerIter, aelWeight)
}

sempl_grad <- function(weights, y, b_r, o_r, innerTol, maxInnerIter, aelWeight) {
    .Call('_empLikSem_sempl_grad', PACKAGE = 'empLikSem', weights, y, b_r, o_r, innerTol, maxInnerIter, aelWeight)
}

naive_sempl_lrt <- function(weights, y, b_r, o_r, innerTol, maxInnerIter, aelWeight) {
    .Call('_empLikSem_naive_sempl_lrt', PACKAGE = 'empLikSem', weights, y, b_r, o_r, innerTol, maxInnerIter, aelWeight)
}

naive_sempl_grad <- function(weights, y, b_r, o_r, innerTol, maxInnerIter, aelWeight) {
    .Call('_empLikSem_naive_sempl_grad', PACKAGE = 'empLikSem', weights, y, b_r, o_r, innerTol, maxInnerIter, aelWeight)
}

naive_semplC <- function(weights, y, b_r, o_r, innerTol, maxInnerIter, aelWeight) {
    .Call('_empLikSem_naive_semplC', PACKAGE = 'empLikSem', weights, y, b_r, o_r, innerTol, maxInnerIter, aelWeight)
}

