// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// sempl_lrt
double sempl_lrt(arma::vec weights, arma::mat y, arma::mat b_r, arma::mat o_r, double innerTol, int maxInnerIter, double aelWeight);
RcppExport SEXP _empLikSem_sempl_lrt(SEXP weightsSEXP, SEXP ySEXP, SEXP b_rSEXP, SEXP o_rSEXP, SEXP innerTolSEXP, SEXP maxInnerIterSEXP, SEXP aelWeightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type b_r(b_rSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type o_r(o_rSEXP);
    Rcpp::traits::input_parameter< double >::type innerTol(innerTolSEXP);
    Rcpp::traits::input_parameter< int >::type maxInnerIter(maxInnerIterSEXP);
    Rcpp::traits::input_parameter< double >::type aelWeight(aelWeightSEXP);
    rcpp_result_gen = Rcpp::wrap(sempl_lrt(weights, y, b_r, o_r, innerTol, maxInnerIter, aelWeight));
    return rcpp_result_gen;
END_RCPP
}
// semplC
Rcpp::List semplC(arma::vec weights, arma::mat y, arma::mat b_r, arma::mat o_r, double innerTol, int maxInnerIter, double aelWeight);
RcppExport SEXP _empLikSem_semplC(SEXP weightsSEXP, SEXP ySEXP, SEXP b_rSEXP, SEXP o_rSEXP, SEXP innerTolSEXP, SEXP maxInnerIterSEXP, SEXP aelWeightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type b_r(b_rSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type o_r(o_rSEXP);
    Rcpp::traits::input_parameter< double >::type innerTol(innerTolSEXP);
    Rcpp::traits::input_parameter< int >::type maxInnerIter(maxInnerIterSEXP);
    Rcpp::traits::input_parameter< double >::type aelWeight(aelWeightSEXP);
    rcpp_result_gen = Rcpp::wrap(semplC(weights, y, b_r, o_r, innerTol, maxInnerIter, aelWeight));
    return rcpp_result_gen;
END_RCPP
}
// sempl_grad
arma::vec sempl_grad(arma::vec weights, arma::mat y, arma::mat b_r, arma::mat o_r, double innerTol, int maxInnerIter, double aelWeight);
RcppExport SEXP _empLikSem_sempl_grad(SEXP weightsSEXP, SEXP ySEXP, SEXP b_rSEXP, SEXP o_rSEXP, SEXP innerTolSEXP, SEXP maxInnerIterSEXP, SEXP aelWeightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type b_r(b_rSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type o_r(o_rSEXP);
    Rcpp::traits::input_parameter< double >::type innerTol(innerTolSEXP);
    Rcpp::traits::input_parameter< int >::type maxInnerIter(maxInnerIterSEXP);
    Rcpp::traits::input_parameter< double >::type aelWeight(aelWeightSEXP);
    rcpp_result_gen = Rcpp::wrap(sempl_grad(weights, y, b_r, o_r, innerTol, maxInnerIter, aelWeight));
    return rcpp_result_gen;
END_RCPP
}
// naive_sempl_lrt
double naive_sempl_lrt(arma::vec weights, arma::mat y, arma::mat b_r, arma::mat o_r, double innerTol, int maxInnerIter, double aelWeight);
RcppExport SEXP _empLikSem_naive_sempl_lrt(SEXP weightsSEXP, SEXP ySEXP, SEXP b_rSEXP, SEXP o_rSEXP, SEXP innerTolSEXP, SEXP maxInnerIterSEXP, SEXP aelWeightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type b_r(b_rSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type o_r(o_rSEXP);
    Rcpp::traits::input_parameter< double >::type innerTol(innerTolSEXP);
    Rcpp::traits::input_parameter< int >::type maxInnerIter(maxInnerIterSEXP);
    Rcpp::traits::input_parameter< double >::type aelWeight(aelWeightSEXP);
    rcpp_result_gen = Rcpp::wrap(naive_sempl_lrt(weights, y, b_r, o_r, innerTol, maxInnerIter, aelWeight));
    return rcpp_result_gen;
END_RCPP
}
// naive_sempl_grad
arma::vec naive_sempl_grad(arma::vec weights, arma::mat y, arma::mat b_r, arma::mat o_r, double innerTol, int maxInnerIter, double aelWeight);
RcppExport SEXP _empLikSem_naive_sempl_grad(SEXP weightsSEXP, SEXP ySEXP, SEXP b_rSEXP, SEXP o_rSEXP, SEXP innerTolSEXP, SEXP maxInnerIterSEXP, SEXP aelWeightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type b_r(b_rSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type o_r(o_rSEXP);
    Rcpp::traits::input_parameter< double >::type innerTol(innerTolSEXP);
    Rcpp::traits::input_parameter< int >::type maxInnerIter(maxInnerIterSEXP);
    Rcpp::traits::input_parameter< double >::type aelWeight(aelWeightSEXP);
    rcpp_result_gen = Rcpp::wrap(naive_sempl_grad(weights, y, b_r, o_r, innerTol, maxInnerIter, aelWeight));
    return rcpp_result_gen;
END_RCPP
}
// naive_semplC
Rcpp::List naive_semplC(arma::vec weights, arma::mat y, arma::mat b_r, arma::mat o_r, double innerTol, int maxInnerIter, double aelWeight);
RcppExport SEXP _empLikSem_naive_semplC(SEXP weightsSEXP, SEXP ySEXP, SEXP b_rSEXP, SEXP o_rSEXP, SEXP innerTolSEXP, SEXP maxInnerIterSEXP, SEXP aelWeightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type b_r(b_rSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type o_r(o_rSEXP);
    Rcpp::traits::input_parameter< double >::type innerTol(innerTolSEXP);
    Rcpp::traits::input_parameter< int >::type maxInnerIter(maxInnerIterSEXP);
    Rcpp::traits::input_parameter< double >::type aelWeight(aelWeightSEXP);
    rcpp_result_gen = Rcpp::wrap(naive_semplC(weights, y, b_r, o_r, innerTol, maxInnerIter, aelWeight));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_empLikSem_sempl_lrt", (DL_FUNC) &_empLikSem_sempl_lrt, 7},
    {"_empLikSem_semplC", (DL_FUNC) &_empLikSem_semplC, 7},
    {"_empLikSem_sempl_grad", (DL_FUNC) &_empLikSem_sempl_grad, 7},
    {"_empLikSem_naive_sempl_lrt", (DL_FUNC) &_empLikSem_naive_sempl_lrt, 7},
    {"_empLikSem_naive_sempl_grad", (DL_FUNC) &_empLikSem_naive_sempl_grad, 7},
    {"_empLikSem_naive_semplC", (DL_FUNC) &_empLikSem_naive_semplC, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_empLikSem(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
